# Generated by Django 5.0.6 on 2024-06-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='tema',
            field=models.CharField(choices=[('0', 'Tema 1'), ('1', 'Tema 2'), ('2', 'Tema 3'), ('3', 'Tema 4')], max_length=20),
        ),
    ]
