# Generated by Django 5.0.6 on 2024-06-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0002_alter_propuesta_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='tema',
            field=models.CharField(choices=[('Tema 1', 'Tema 1'), ('Tema 2', 'Tema 2'), ('Tema 3', 'Tema 3'), ('Tema 4', 'Tema 4')], max_length=20),
        ),
    ]
